# Generated by Django 5.2.3 on 2025-06-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('key', models.CharField(choices=[('C', 'C'), ('C#', 'C♯'), ('Cb', 'C♭'), ('D', 'D'), ('D#', 'D♯'), ('Db', 'D♭'), ('E', 'E'), ('E#', 'E♯'), ('Eb', 'E♭'), ('F', 'F'), ('F#', 'F♯'), ('Fb', 'F♭'), ('G', 'G'), ('G#', 'G♯'), ('Gb', 'G♭'), ('A', 'A'), ('A#', 'A♯'), ('Ab', 'A♭'), ('B', 'B'), ('B#', 'B♯'), ('Bb', 'B♭')], max_length=2)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
