# Generated by Django 5.2.3 on 2025-06-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.CharField(choices=[('C', 'C'), ('C#', 'C♯'), ('Cb', 'C♭'), ('D', 'D'), ('D#', 'D♯'), ('Db', 'D♭'), ('E', 'E'), ('E#', 'E♯'), ('Eb', 'E♭'), ('F', 'F'), ('F#', 'F♯'), ('Fb', 'F♭'), ('G', 'G'), ('G#', 'G♯'), ('Gb', 'Gurl♭'), ('A', 'A'), ('A#', 'A♯'), ('Ab', 'A♭'), ('B', 'B'), ('B#', 'B♯'), ('Bb', 'B♭')], max_length=2),
        ),
    ]
