# Generated by Django 5.2.3 on 2025-06-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_song_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='url',
        ),
        migrations.AddField(
            model_name='song',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.CharField(choices=[('C', 'C'), ('C#', 'C♯'), ('Cb', 'C♭'), ('D', 'D'), ('D#', 'D♯'), ('Db', 'D♭'), ('E', 'E'), ('E#', 'E♯'), ('Eb', 'E♭'), ('F', 'F'), ('F#', 'F♯'), ('Fb', 'F♭'), ('G', 'G'), ('G#', 'G♯'), ('Gb', 'Gurl♭'), ('A', 'A'), ('A#', 'A♯'), ('Ab', 'A♭'), ('B', 'B'), ('B#', 'B♯'), ('Bb', 'B♭')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
