# Generated by Django 5.2.3 on 2025-06-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_remove_song_url_song_version_alter_song_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField(null=True)),
                ('death', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='key',
        ),
        migrations.AddField(
            model_name='song',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='mode',
            field=models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('', '')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='tonic_accidental',
            field=models.CharField(blank=True, choices=[('#', '♯'), ('##', '♯♯'), ('b', '♭'), ('bb', '♭♭'), ('', '')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='tonic_base',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1, null=True),
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='songs.artist'),
        ),
    ]
