# Generated by Django 5.2.3 on 2025-06-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_artist_remove_song_key_song_filename_song_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='filename',
            field=models.CharField(max_length=200),
        ),
    ]
