# Generated by Django 5.2.4 on 2025-07-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_song_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name', 'version')},
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='song',
            name='filename',
        ),
    ]
