# Generated by Codex on 2026-05-02

from django.db import migrations, models


def backfill_song_identity_fields(apps, schema_editor):
    Song = apps.get_model('songs', 'Song')
    for song in Song.objects.all():
        artists = list(song.artist.order_by('name').values_list('name', flat=True))
        song.artist_text = ', '.join(artists)
        song.storage_key = song.file.name or f'legacy-song-{song.pk}.pdf'
        song.save(update_fields=['artist_text', 'storage_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_alter_artist_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='storage_key',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.RunPython(backfill_song_identity_fields, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name', 'artist_text', 'version')},
        ),
    ]
