# Generated by Django 5.2.3 on 2025-06-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0005_alter_song_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artists', models.ManyToManyField(to='songs.artist')),
                ('songs', models.ManyToManyField(to='songs.song')),
            ],
        ),
    ]
