# Generated by Django 5.2.13 on 2026-05-01 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_profile_user'),
        ('songs', '0006_alter_artist_options_alter_song_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_liked_songs', models.BooleanField(default=False)),
                ('songs', models.ManyToManyField(blank=True, related_name='playlists', to='songs.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_playlist_name_per_user'), models.UniqueConstraint(condition=models.Q(('is_liked_songs', True)), fields=('user', 'is_liked_songs'), name='unique_liked_songs_playlist_per_user')],
            },
        ),
    ]
