# Generated by Django 5.2.13 on 2026-05-01 12:40

from django.db import migrations, models


def populate_song_order(apps, schema_editor):
    Playlist = apps.get_model('authorization', 'Playlist')

    for playlist in Playlist.objects.all():
        playlist.song_order = list(playlist.songs.values_list('id', flat=True))
        playlist.save(update_fields=['song_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='song_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(populate_song_order, migrations.RunPython.noop),
    ]
